apiVersion: v1
kind: Pod
metadata:
  name: apache-mysql-php-pod
  namespace: test2
  labels:
    app: webapp
spec:
  containers:
  - name: apache
    image: php:7.4-apache
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: /var/www/html
      name: web-content
    ports:
    - containerPort: 80
  - name: mysql
    image: mysql:5.7
    resources:
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "512Mi"
        cpu: "500m"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: partage_de_recettes
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      value: root
    ports:
    - containerPort: 3306
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - mysqladmin ping -h 127.0.0.1
      initialDelaySeconds: 30
      periodSeconds: 10
  volumes:
  - name: web-content
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: apache-mysql-php-service
  namespace: test2
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: apache-mysql-php-external
  namespace: test2
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30123  # Vous pouvez spécifier un port entre 30000-32767