- name: Déployer les pods Kubernetes avec Minikube
  hosts: localhost
  become: yes
  tasks:
    - name: Démarrer Minikube (si ce n'est pas déjà fait)
      shell: |
        minikube start --driver=docker
      register: minikube_status
      changed_when: minikube_status.stdout | search("Started")

    - name: Vérifier que Minikube est démarré
      command: minikube status
      register: minikube_status_check

    - name: Déployer les pods à partir du fichier YAML
      shell: |
        kubectl apply -f /root/yamls/{{ item }}
      loop:
        - pod-deployment.yaml
      when: minikube_status_check.stdout | search("Running")
      notify:
        - Vérifier les pods déployés

    - name: Exposer le service web
      shell: |
        kubectl expose pod <nom-du-pod> --type=NodePort --name=web-service --port=80 --target-port=80
      when: minikube_status_check.stdout | search("Running")

    - name: Récupérer l'URL du service exposé
      shell: |
        minikube service web-service --url
      register: service_url
      when: minikube_status_check.stdout | search("Running")

  handlers:
    - name: Vérifier les pods déployés
      shell: kubectl get pods -A
      when: minikube_status_check.stdout | search("Running")
