---
- name: Deploy Pods on Minikube
  hosts: localhost
  tasks:
    - name: Apply Kubernetes YAML files
      k8s:
        kubeconfig: "/root/.kube/config"  # Assurez-vous que le kubeconfig est monté correctement
        state: present
        src: "{{ yamlPath }}/*.yml"  # Applique tous les fichiers YAML dans le répertoire spécifié
