CREATE DATABASE IF NOT EXISTS mydatabase;
USE mydatabase;

GRANT ALL PRIVILEGES ON mydatabase.* TO 'myapp'@'localhost';

CREATE TABLE IF NOT EXISTS comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT NOT NULL
);

FLUSH PRIVILEGES;

