pipeline {
    agent {
        docker { image 'docker:dind' }
    }
    environment {
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'  // Jenkins credentials
    }
    stages {
        stage('Build App') {
            steps {
                sh 'docker build -t my-simple-app:latest ./app'
                sh 'docker build -t my-database:latest ./db'
            }
        }
        stage('Push to Registry') {
            steps {
                withDockerRegistry([credentialsId: "${DOCKER_CREDENTIALS_ID}", url: '']) {
                    sh 'docker tag my-simple-app:latest yourdockerhubusername/my-simple-app:latest'
                    sh 'docker tag my-database:latest yourdockerhubusername/my-database:latest'
                    sh 'docker push yourdockerhubusername/my-simple-app:latest'
                    sh 'docker push yourdockerhubusername/my-database:latest'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f kubernetes/'
            }
        }
    }
}
