pipeline {
    agent any

    environment {
        REGISTRY_URL = "chocomacs/devops" // Registre Docker local
        DOCKER_USERNAME = 'cholat.julien@free.fr'
        DOCKER_PASSWORD = '$Dzmb4wQvFnXSmHuj6UmBsJo7L37tf254!azk%!EywS2wkV9cxgoVXNtaw$sEXK9jthLPBNfMRxKvFfV^m$E^@Nda^GeZqL*7!LR95fDRFTK#tQa$2y44KymeTYRj3Sd'
        
    }
    
        
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/ChocoMacs/ProjetDEVOPS.git'
            }
        }
        
        stage('Login to Docker') {
            steps {
                script {
                    sh "minikube start"
                    sh 'echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin'
                }
            }
        }
        
        stage('Build/Push Containers app') {
            steps {
                dir('./testchoco/app') { // S'assurer que le bon répertoire est utilisé
                    script {
                        // Construire et pousser l'image de la base de données
                        sh "docker build -t ${env.REGISTRY_URL}:myapp ."
                        sh "docker push ${env.REGISTRY_URL}:myapp"
                    }
                }
            }
        }
        
        stage('Build/Push Containers mydb') {
            steps {
                dir('./testchoco/db') { // S'assurer que le bon répertoire est utilisé
                    script {
                        // Construire et pousser l'image de la base de données
                        sh "docker build -t ${env.REGISTRY_URL}:mydb ."
                        sh "docker push ${env.REGISTRY_URL}:mydb"
                    }
                }
            }
        }

        stage('Test Locally') {
            steps {
                dir('./testchoco') {
                    sh '''
                    docker-compose up -d
                    sleep 10
                    docker-compose down
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('./testchoco/kubernetes') { // Naviguer dans le répertoire Kubernetes
                    sh '''
                    kubectl apply -f deployement.yaml
                    kubectl apply -f service.yaml
                    kubectl apply -f pvc.yaml
                    '''
                }
            }
        }
    }
}
