pipeline {
    agent {
        docker {
            image 'docker:latest'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker-compose build'
            }
        }
        stage('Test') {
            steps {
                sh 'docker-compose up -d'
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                kubectl apply -f kubernetes/deployment.yaml
                kubectl apply -f kubernetes/service.yaml
                kubectl apply -f kubernetes/pvc.yaml
                '''
            }
        }
    }
}
