apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: chocomacs/devops:myapp  # Assurez-vous que l'image existe sur Docker Hub
          ports:
            - containerPort: 5000
          
        - name: db
          image: chocomacs/devops:mydb  # Assurez-vous que l'image existe sur Docker Hub
          ports:
            - containerPort: 3306
          env:
            - name: DATABASE_HOST
              value: "db-service"  # Service pour la base de données
            <- name: DATABASE_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "mydatabase"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc  # Assurez-vous que le PVC est défini dans pvc.yaml
