apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-simple-app
  template:
    metadata:
      labels:
        app: my-simple-app
    spec:
      imagePullSecrets: []  # Pas besoin de secrets si le registre est ouvert
      containers:
      - name: app
        image: lchocomacs/devops:myapp  # Image de l'application
        ports:
        - containerPort: 5000
      - name: db
        image: chocomacs/devops:mydb  # Image pour la base de données
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: examplepassword
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: my-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
