apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html-volume
  volumes:
  - name: html-volume
    configMap:
      name: html-page-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-page-configmap
data:
  index.html: |
    <html>
      <head><title>Welcome to Nginx!</title></head>
      <body>
        <h1>Hello, welcome to my web page served by Nginx in Kubernetes!</h1>
      </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
