version: '3.8'

services:
  db:
    image: mysql:8.0.40
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myapp
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: myapp
    environment:
      DATABASE_HOST: db
      DATABASE_USER: myapp
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydatabase
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
    driver: local
