auth_enabled: false

server:
  http_listen_port: 3100
  log_level: debug

ingester:
  chunk_target_size: 1048576
  max_chunk_age: 1h

distributor:
  shard_by_all_labels: true

frontend:
  log_queries_longer_than: 5s

limits_config:
  max_query_length: 25h
  max_query_size: 1048576

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 7d
